#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
copy_exec /sbin/drbdadm /sbin/drbdadm
copy_exec /sbin/drbdmeta /sbin/drbdmeta
copy_exec /sbin/drbdsetup /sbin/drbdsetup
cp -rp /etc/drbd.conf $DESTDIR/etc/
cp -rp /etc/drbd.d $DESTDIR/etc/
mkdir -p $DESTDIR/var/lib/drbd
